### PR TITLE
Added rust support in LGSL

### PR DESCRIPTION
**Pull request by acsid**
I fixed the mess ive done the last time.

### CODE REVIEW

**Comment by Zorrototo** [comment]
That's correct but maybe sort it alphabetically in order to keep... order :D

**Comment by rocco27** [comment]
What was wrong with GameQ? It works perfectly with Rust.
You can extend LGSL by Rust, but then do not forget to add lgsl_port_conversion($type, $c_port, $q_port, $s_port) as well!

**Comment by Zorrototo** [comment]
I don't think there is something wrong with GameQ, but why not having both available? :) (personally I prefer LGSL :D)

**Comment by acsid** [comment]
I added Rust to LGSL mainly to get it working into the LGSL server list. Let me take a look at that part.

**Comment by Zorrototo** [comment]
It actually currently work with LGSL if you setup as a source server :) but yeah it is better to have it with proper name :D

**Comment by rocco27** [comment]
Okey I got it.

**Pull request merged**
