### PR TITLE
Language Support in JS

### PR DESCRIPTION
**Pull request by own3mall**

### CODE REVIEW

**Comment by own3mall** [comment]
@Adjokip - Can you think of any security issues this may cause?  I can't...

**Comment by own3mall** [comment]
@Adjokip , I merged it, but I'd still like to know your opinion on any potential security issues that might be opened.

**Comment by Adjokip** [comment]
I think the only issue would be is if the language constant contained some malicious data. But if everything is reviewed prior to pushing, it should be fine. htmlentities and/or striptags would resolve that possible issue.

Another possible issue would be is anywhere with define and a password or sensitive data as that would be exposed to the user. But I don't believe that happens anywhere.

**Comment by own3mall** [comment]
Thanks @Adjokip, I thought of those use cases as well.  It looks like it has to be htmlentities anyways to get the French characters right, so that's done now too ;)  -  If you can think of any other risk, please let me know :+1:

**Pull request merged**
