### PR TITLE
Add chinese language

### PR DESCRIPTION
**Pull request by shinegod**
Add chinese language

### CODE REVIEW

**Comment by Zorrototo** [comment]
OGP translations will only be made through Transifex. 

https://app.transifex.com/opengamepanel/ogp/dashboard/

Chinese is not available there though. I'm trying to add it, then will try to see if I can upload your changes, we can the nsee how far the translation is and if we add it officially.

There are MANY language requests but adding a language nobody will support and maintain is kinda pointless. I guess Chinese may be good to add as the potential translators pool should be big so maybe we get one or two people interested in translating properly OGP.

**Comment by Zorrototo** [comment]
I added Chinese to Transifex. Translation can be done there now.

Will see to add it to OGP officially later as there are things to do before it could be possible to send changes directly from Transifex to OGP's GitHub.

**Comment by shinegod** [comment]
OK, I have applied to join and am waiting for review.

**Comment by Zorrototo** [comment]
You have been added to the Chinese translator team ;)

**Comment by Zorrototo** [comment]
OK, @own3mall did what was required for the sync to happen, there is now a new Chinese(China) language available in OGP, and translation to Panel and modules should be synchronized with Transifex now.

**Pull request closed without merging**
