### PR TITLE
TS3 Admin Show Only assgined Agent For users

### PR DESCRIPTION
**Pull request by Obada8**

### CODE REVIEW

**Comment by own3mall** [comment]
Looks OK, but you need to create the definition for your new function in database.php before I will merge.

**Comment by own3mall** [comment]
Like this:

https://github.com/OpenGamePanel/OGP-Website/commit/c62566ae2c0b0c95c0ec3114a2f265d3d196dc19

Must be done anytime you add new functions to either database files.

**Comment by own3mall** [comment]
Meh, I'll do it for you this time, but next time, make sure you do that!

**Comment by Obada8** [comment]
oh, sorry hhhhh,, i was sleeping :p,ok next time no sleep :v

**Pull request merged**
