### PR TITLE
Assigning Multiple Cores to Servers

### PR DESCRIPTION
**Pull request by Adjokip**
Fulfilling a feature request posted [here](http://www.opengamepanel.org/forum/viewthread.php?thread_id=5285) by @FarukGamer - these small changes allow you to assign multiple cores to a server.

It requires a change in the ogp_game_mods table, changing the cpu_affinity column from a varchar(2) to varchar(64) (a maximum possible of 32 cores, as the core info is seperated by commas, eg, 0,1,2)

It doesn't require anything to be changed on the agent side - as the agent just uses `taskset`, which accepts cores the way I mentioned above.

It'll also attempt to verify that a valid core has been selected. As in, if you've got 4 cores, the user cannot edit the checkboxes and change the value of one to a non-existing core. Or edit the checkbox value to a
non-numeric value. Doing so will default the field to 'NA', which the agent handles.

It's mostly srcds servers I've hosted for in the past which don't benefit from multiple cores. Although, I could see this being useful for some games.

### CODE REVIEW

**Comment by FarukGamer** [comment]
I did wrote it already on the forum. Anyways, thank you for fulfilling this request 😃

**Comment by own3mall** [comment]
Does this impact Windows?

**Comment by Adjokip** [comment]
@own3mall Initially it impacted Windows. But it should work now.

Don't have a VM up for testing, but the output of `$result` is as you'd expect to pass to the /affinity flag.

**Comment by FarukGamer** [comment]
Does this works with Linux?

**Comment by Adjokip** [comment]
@FarukGamer Linux Mint is what I tested it on. So it should be working on those environments.

`while sleep 1; do ps -Uogp_agent -Lo pid,lwp,psr,comm | egrep 'PID' && echo -e "\n"; done` shows the cores being assigned properly.

**Comment by FarukGamer** [comment]
Alright

**Comment by own3mall** [comment]
Still need someone to test this on Windows, but I guess it's good for now.

**Comment by FarukGamer** [comment]
Now I have updated the Panel and Agent without any problems. But strangely, the function is missing to assign it to multiple cores.

http://prntscr.com/eia9lc

**Comment by Adjokip** [comment]
@FarukGamer Yeah. I accidentally removed this when working on the auto-update feature, after creating another branch. Previously I was just submitting changes to my master branch, which, evidently isn't very practical when working on multiple features :P

I resubmitted the PR in #61. Also got a chance to test it on Windows, works there.

**Comment by FarukGamer** [comment]
Oh I have not seen it, sorry

**Comment by FarukGamer** [comment]
It seems so that the selected boxes do not save properly. I have noticed it after I have reloaded the page.

**Comment by Zorrototo** [comment]
I tried to assign different cores to a game server, and yeah they seem to not save when your refresh the edit page, none is selected. Database however has a value saved so I guess it works.

Note also that there is currently a bug with the module installation/update so be sure to check that thread http://www.opengamepanel.org/forum/viewthread.php?thread_id=5295 or your database will surely not have the proper modification to store the changes to cpu affinity. I also see the taskset command in the server startup script so I think it works properly.

The problem is that it does not tick the already set CPU so this should be changed if possible to reflect the current selected CPU.

**Comment by FarukGamer** [comment]
taskset: failed to parse CPU list: 0, taskset: failed to parse CPU list: 0, taskset: failed to parse CPU list: 0, taskset: failed to parse CPU list: 0,

**Comment by FarukGamer** [comment]
taskset: failed to parse CPU list: 0

This is what I get now

**Comment by Adjokip** [comment]
@FarukGamer That'll be because the query failed to run from modules.php.

Modify it manually in the meantime:
```sql
ALTER TABLE `ogp_game_mods` modify column `cpu_affinity` varchar(64) null AFTER `extra_params`, comment = 'utf8mb4_general_ci';
```

It'll be fixed once @Zorrototo's PR is accepted. The query fails because of a syntax error. Which I should have noticed. Sorry.

**Comment by Adjokip** [comment]
That's because the query fails to run from modules.php.

It'll work once @Zorrototo's PR is accepted.

In the meantime, you can run this to fix it:

```sql
ALTER TABLE `ogp_game_mods` modify column `cpu_affinity` varchar(64) null AFTER `extra_params`, comment = 'utf8mb4_general_ci';
```

I should have noticed the SQL error in modules.php. Sorry. If you notice the value is 0, ... so it's still at VARCHAR(2) rather than VARCHAR(64).

**Pull request merged**
