### PR TITLE
Added Stationeers XML for linux servers

### PR DESCRIPTION
**Pull request by Talung**
Added a basic Stationeers XML and lgsl_protocol adjustments for Linux64 bit.

### CODE REVIEW

**Comment by Zorrototo** [comment]
You can add a Stationeers icon in OGP /images/icons/stationeers.png

In protocol.php I think you made it wrong you switche C_port and Q_port should be in theory:
`            case "stationeers"      : $c_to_q = -485;   $c_def = 27500; $q_def = 27015; $c_to_s = 0;    break;`

as documentation says:

```
 -gameport integer UDP port for game. Avoid to set 27015-27020. 
It's steam's local server query ports.
-**updateport**  integer UDP port for **steam query**
```
```
gameport : 27500
 **updateport : 27015**
```

actually like in the protocol.php file I provided on the forum

**Comment by Talung** [comment]
Updated the lgsl_protocol with the changes.  Icon png file should be there in the correct place.

**Comment by Zorrototo** [comment]
I didn't see the icon when I first looked, yeah it is there.

**Comment by Zorrototo** [comment]
👍 seems good to me, if you have checked everything was working good on your side.

**Comment by Talung** [comment]
Been running that version for over a week now.  No issues.  Just had a different port gap, which is fixed now in the last couple of days.  I have also setup a fresh test server to test this out, and works fine.

**Pull request merged**
