### PR TITLE
Fixed Copyrights in the files

### PR DESCRIPTION
**Pull request by rocco27**

### CODE REVIEW

**Comment by rocco27** [comment]
Not ready yet. :)

**Comment by rocco27** [comment]
It is done now.

**Comment by rocco27** [comment]
I found one more Copyright error on the forum, it is on the footer, above the GitHub text: 

> Copyright © OGP 2016

**Comment by own3mall** [comment]
As far as I know, the copyright doesn't really need to be updated every year.  

But, since you already did it, here we go!  Thanks for your help!

**Comment by rocco27** [comment]
No problem.

**Pull request merged**
