### PR TITLE
Added bRawSockets support for ArkSE

### PR DESCRIPTION
**Pull request by MrCraigTunstall**
This is to better aid those whom have to use the bRawSockets command line in order for clients to join the server.

### CODE REVIEW

**Comment by Zorrototo** [comment]
Are you sure about that? Isn't the command line parameter simply `bRawSockets` instead of `bRawSockets=true`? That's what I read on the official wiki, and if so then use a _checkbox_ instead of a _select_.

Also in that case, by using bRawSockets, wouldn't it mess up the way OGP works with this game server? would the Panel query work properly? (expecting game port + 19238 for query and not game port + 1 from what I read for bRawSockets)?

Did you test your XML?

**Comment by MrCraigTunstall** [comment]
Yes, I tested the XML and all works correctly. I'll alter the XML later to just have ?bRawSockets than ?bRawSockets=True

**Comment by MrCraigTunstall** [comment]
?bRawSockets and ?bRawSockets=True works by the looks of it.

**Comment by Zorrototo** [comment]
and ?bRawSockets=False also works in the command line?

**Comment by MrCraigTunstall** [comment]
Indeed as ?bRawSockets=False is the default. It's not required to put ?bRawSockets=False and can alter the XML to be an tickbox. Added it as True and False because some cases ?bRawSockets=True works whereas ?bRawSockets did not for a few server owners.

**Comment by Zorrototo** [comment]
What I mean is does ?bRawSockets=False properly disable this feature because if the parameter ?bRawSockets=False ?bRawSockets=True and ?bRawSockets is interpreted the same in command line (because as I read in the wiki or on steam from devs, the parameter is just ?bRawSockets), then the tickbox is mandatory.

**Comment by MrCraigTunstall** [comment]
Altered as requested, tested again to verify and works when adding that to the commandline. :)

**Comment by Zorrototo** [comment]
OK, merging changes then.

**Comment by Zorrototo** [comment]
For reference, using the parameter will need to have game port +1 UDP available, opened, and forwarded properly for this feature to work.

**Pull request merged**
