### PR TITLE
Updated German Lang

### PR DESCRIPTION
**Pull request by fabm3n**
Updated some German Lang files.

### CODE REVIEW

**Comment by rocco27** [comment]
@fabm3n Please use Transifex instad of editing any php files, because we do not accept translations this way anymore. Create a free account on Trasifex site and join to OGP Translators.

Informations on the OGP forum: https://opengamepanel.org/forum/viewthread.php?thread_id=5057
Transifex site: https://www.transifex.com/
OGP project on Trasifex: https://www.transifex.com/opengamepanel/ogp/dashboard/

**Comment by fabm3n** [comment]
Oh okay. I visited your forum and saw this thread https://opengamepanel.org/forum/viewthread.php?thread_id=5047 so i started modifying. I will change all to transiflex ^^

**Comment by fabm3n** [comment]
In which interval where the translations updated in Github? And how can I get a German Reviewer or Coordinator?

**Comment by rocco27** [comment]
We synchronize Transifex and GitHub offen or when it is necessary. If you want to be a Reviewer you can sign up to the position, but first just translate much as possible. :)

**Comment by fabm3n** [comment]
Okay ^^ so lets Translating ^^

**Pull request closed without merging**
