### PR TITLE
spigotmc_linux.xml

### PR DESCRIPTION
**Pull request by SinaloenseMx**

### CODE REVIEW

**Comment by own3mall** [comment]
@Obada8 or @rocco27, can you please review and test this XML this when you get a chance?  Thanks!

**Comment by Obada8** [comment]
@own3mall because i am used old version of ogp these moment, i need to ask if this xml need any change in protocols ?
* my panel protocol version is : f71e6c46f8042036bd97258f32470b548d8d6a33

but anyway i will test it and send result here based on this version.

**Comment by SinaloenseMx** [comment]
@Obada8 Download the latest version of spigot from here [https://getbukkit.org/spigot](url) and rename it to "spigot.jar"

**Comment by Zorrototo** [comment]
Why should people download it if your XML tries to create it? Maybe I don't understand how minecraft games work though.

**Comment by SinaloenseMx** [comment]
You're right, but people also download the version that they like or need for his server.
I have no idea which version i download by Rsync.

I will use rsync and then I will return.

pd: Sorry, I was try to contribute.
pd2: How should be the xml file?

**Comment by Zorrototo** [comment]
The problem here is  that your XML is made to use spigot.jar as the server executable right? and your XML creates a startup script named spigot.jar (previously spigot_run). If you replace the startup script spigot.jar with spigot.jar downloaded from spigot website, it will just not work as intended for example the auto update or update build tools startup parameters will not work at all..

> pd: Sorry, I was try to contribute.
seriously? don't be that guy.. I said nothing bad so don't try to be a victim.

So what was the problem in the first place with the original XML? because in my opinion you did not fix the XML at all it is exactly the same, but with a conflict in files (replacing startup script with real spigot.jar server executable) and a forced parameter at start of command line which was already inside the original startup script spigot_run (but as you replace startup script spigot.jar with real server executable name it kinda works then).

I can't run this XML nor the original one I don't have and don't want to install java, but from the look of it, in my opinion, your XML is wrong.

**Comment by SinaloenseMx** [comment]
I was wrong and that's why I apologize.

**Problem 1:**
<cli_template>-Xincgc %XMX% -XX:MaxPermSize=128M -jar spigot.jar nogui</cli_template>
**Should be:**
<cli_template>-Xincgc %XMX% -XX:MaxPermSize=128M -jar minecraft_server.jar nogui</cli_template>

**"Problem 2":**
# java -Xincgc -Xmx1024M -XX:MaxPermSize=128M -jar spigot.jar nogui
**Should be:**
# java -Xincgc -Xmx1024M -XX:MaxPermSize=128M -jar minecraft_server.jar nogui

**Problem 3:**
mv spigot-*.jar spigot.jar
**Should be:**
mv spigot-*.jar minecraft_server.jar

**Suggestion 1:**
<max_user_amount>32</max_user_amount>
**My suggestion:**
<max_user_amount>1000</max_user_amount>

Suggestion 2:
<caption>Max RAM</caption>
<desc>How much memory? for example: 1024M</desc>
**My suggestion:**
<caption>RAM</caption>
<desc>Maximum RAM capacity for the server, example: 1024 M</desc>

**Who does -autoupdate?, I do not understand its function in the code**
<param key="-autoupdate" type="checkbox_key_value">
	  <caption>Update the server before starting</caption>
	  <desc>Will compile the server from source, this process may take some minutes.</desc>
</param>

**Comment by Zorrototo** [comment]
I will try to explain what I understand of how it works. I will talk about original XML here.


After installing from Rsync, it run the post install script, which will create the server starter file `spigot_run`.

`spigot_run` will take the parameters from the Panel when you start the game server. If you check the boxes for `autoupdate` and `updateBuildTools` it will download latest BuildTools.jar from https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar and compile the latest spigot-xxxx.jar file, then move spigot-xxxx.jar to spigot.jar.

For me the XML looks fine so I still wonder what is wrong. The only thing I would change would be:
```
<caption>RAM</caption>
<desc>Maximum RAM capacity for the server, example: 1024M</desc>
```
with the M attached to 1024, as I previously told you, if you put an example it must match what the user needs to type, or the example is wrong.


Let try something. Install new spigot server with the original XML. Tick the two checkboxes  `autoupdate` and `updateBuildTools` and start the server. Let it do its job (downloading and compiling the files, and starting the server).

So does it work? If not what happens exactly?

**Comment by Adjokip** [comment]
The current XML works fine for me and does everything as @Zorrototo described.

`version` command after compiling and automatically starting: `This server is running CraftBukkit version git-Spigot-625bc00-d09304e (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)`

I don't think it's necessary to move spigot.jar to minecraft_server.jar. I'd only update what's mentioned above and the max players... everything else seems to function fine.

**Comment by SinaloenseMx** [comment]
This happens when I do Rsync installation:
```
##### Welcome to the Opengamepanel.org rsync server ####

#     This server is located in New York, USA

#

#     Thank you for using Opengamepanel, and supporting open source!

#

##########################################################



receiving incremental file list

./

minecraft_server.jar



sent 62 bytes  received 5521203 bytes  1577504.29 bytes/sec

total size is 6146939  speedup is 1.11
```

Generated files:
[https://preview.ibb.co/i9yA5a/Screenshot_2.png](url)

This happens when I try start the server:
```
Starting server with command: java -Xincgc -Xmx500M -XX:MaxPermSize=128M -jar spigot.jar nogui

Error: Unable to access jarfile spigot.jar
```
Rsync download this "minecraft_server.jar", the original xml has a problem.
That's why I suggest these changes: [https://github.com/OpenGamePanel/OGP-Website/pull/92#issuecomment-290290431](url)

**Comment by Zorrototo** [comment]
Yeah I already told you the Rsync server send default minecraft server files. but this is not related directly to the XML but the Rsync server itself. Anyway, did you read and did this?
```
Let try something. Install new spigot server with the original XML. Tick the two checkboxes autoupdate and updateBuildTools and start the server. Let it do its job (downloading and compiling the files, and starting the server).

So does it work? If not what happens exactly?
```

**Comment by Zorrototo** [comment]
hello?

**Comment by Zorrototo** [comment]
As we say in France "Pas de nouvelles, bonne nouvelle!" which can be translated as "No news, good news!" or something similar... I guess there is no problem afterall?

**Comment by Obada8** [comment]
in arabic "الصمت علامة الرضا" translated to "Silence sign acceptance" :p

**Comment by Zorrototo** [comment]
I guess this can be closed as there is no response at all (and apparently no problem at all).

**Comment by Zorrototo** [comment]
"Qui ne dit mot, consent" => "Silence is consent"

**Comment by own3mall** [comment]
HELLO

**Pull request closed without merging**
