### PR TITLE
Group fix.

### PR DESCRIPTION
**Pull request by Adjokip**
Fixes http://www.opengamepanel.org/forum/viewthread.php?thread_id=5115

Must've overlooked this when testing and working on multiple projects.

### CODE REVIEW

**Comment by Zorrototo** [comment]
Hiho Adjokip. I just wonder are you a OGP forum member? I tried to find who you are if you're from OGP forum but can't find :P

**Comment by Adjokip** [comment]
@Zorrototo I visit the forum throughout the day. Attempted to make an account a few days ago but never got the activation email. Signed up with Adjo // ogp@adjo.me

**Comment by rocco27** [comment]
I also requested new password before and never got any mail. I think something is wrong with the mail settings in the forum...

**Comment by Zorrototo** [comment]
Ho OK :) 

For sure new members seems to register from what I see on forums right now :P maybe some bots :D

See you on forums if it works later or when admins come back from holidays.

**Comment by own3mall** [comment]
Email server works just fine.  You need to check your Spam folder.  If it's not there, your email provider for some reason thinks the IP address for our server should be blacklisted.  There are some really stupid email blacklists out there that do blacklist my server for some unknown reason.  I can assure you our servers DO NOT send spam though.  Gmail email accounts should receive emails.  Not sure about others since I don't know how they're configured.

**Pull request merged**
