### PR TITLE
Fix for languages where text takes two lines in the button

### PR DESCRIPTION
**Pull request by Zorrototo**

### CODE REVIEW

**Comment by own3mall** [comment]
What happens if the height is removed altogether?  The button should auto-adjust in size?  We could set a max-height of 100px, but first try it without the height rule.

**Comment by Zorrototo** [comment]
It is not good by removing the height property because then you have buttons with different heights.

**Comment by own3mall** [comment]
And that's a problem because? HTML is usually pretty responsive when no height is set.  Button text should be kept relatively short.  Now because of other languages, we have to increase the height of all buttons to accommodate?  I'm fine with merging this change, but I'm not a fan of fixed pixel heights.  :D

**Comment by Zorrototo** [comment]
It is a problem because it is visually disgusting.

**Comment by Zorrototo** [comment]
By the way, same problem with english lang actually, for example the string "Update from local Master Server" takes two lines too.

**Pull request merged**
