### PR TITLE
Added Rust support in lgsl

### PR DESCRIPTION
**Pull request by acsid**

### CODE REVIEW

**Comment by Zorrototo** [comment]
WTF

**Comment by acsid** [comment]
Hoo sorry i posted the respo change on the wrong branch

**Comment by Zorrototo** [comment]
So...... remove this pull request I guess? This will never be accepted.

**Comment by own3mall** [comment]
It was probably a mistake on his part to include his repo.  Do we have rust in the lgsl?  If not, please remove the changed updater to acsid respo commit, and I'll commit the rest into master.

**Comment by Zorrototo** [comment]
Yeah no we have GameQ only for Rust. It was OK for his Rust addition to LGSL though.

**Comment by acsid** [comment]
Yeah it was a mistake Also my first pull request ever and wasn't sure how it was working. I now fixed my master branch au put my repo commit on an other branch.

**Comment by own3mall** [comment]
If you want, please create a new pull request with just changes to LGSL for Rust.  It will be approved and merged if done correctly.

**Comment by own3mall** [comment]
It looks like your branch is quite different now.  I will manually merge your changes to LGSL soon.

**Pull request closed without merging**
