### PR TITLE
add and change

### PR DESCRIPTION
**Pull request by Bebiano86**
add new xml and protocol for RedM servers for linux/windows
modify fivem.xml

### CODE REVIEW

**Comment by Zorrototo** [comment]
Replace in proper alphabetical order in the LGSL protocol. thanks. Also that is cosmetic but I would write with caps the game title "Red Dead Redemption 2 RedM" instead of "Red dead redemption 2 RedM". Can't comment on the other changes as I don't own the game and can't test the server.

**Comment by Bebiano86** [comment]
@Zorrototo 
Thank you, correction made.
Servers tested by me for windows and linux systems

**Comment by Zorrototo** [comment]
I don't own the games so I can not test further, if someone can test to continue forward and integrate or not the change.

**Comment by Zorrototo** [comment]
Seems OK despite the added tabulation at some end of lines. I don't own the games so I can not test further, if someone can test to continue forward and integrate or not the changes.

**Comment by own3mall** [comment]
@Zorrototo 

We'll just go with it for now, and if people complain, then the real testing by those complaining begins.

**Pull request merged**
