### PR TITLE
Avorion server (steam)

### PR DESCRIPTION
**Pull request by bimbam2103**
This is an updated version to use with the avorion server (steam).
Thanks to omano and rocco27 for the great help.

### CODE REVIEW

**Comment by Zorrototo** [comment]
http://www.avorion.net/forum/index.php?topic=973.0 a current bug in Avorion makes it not reachable if the polling port is modified, safer to not set it for now (but will use always the 27003 port for now)

**Comment by bimbam2103** [comment]
Zorrototo is correct. There is a bug in avorion server.

Please ignore the reverts if possible. The pull is correct. The server script works well (except the bug)

**Comment by Zorrototo** [comment]
I sent a modification with GitHub Desktop it appears in my client, seems to be sent, but apparently not because I got 404 error when I click the GitHub icon on my pull request.. weird..

I removed "%POLLING_PORT%" from CLI and the corresponding reserved port. If you can remove it when accepting that will avoid problems for the one unaware of the bug.

**Comment by own3mall** [comment]
Ok, please let us know when we can update it back :)

**Pull request merged**
