### PR TITLE
Include Path fix for XXTEA

### PR DESCRIPTION
**Pull request by oNdsen**
This allows getting access to OGPRemoteLibrary Class from other Modules

### CODE REVIEW

**Comment by own3mall** [comment]
Why did you change the path for XXTEA?  Where is this failing for you?  

In most of the code, lib_remote is loaded like this:

`require_once('includes/lib_remote.php');`

Thus, the active path is still currently the root OGP directory.  If that were not the case, all of the `require_once` calls would fail and prevent further execution of the code if the path weren't correct in the first place.

**Comment by oNdsen** [comment]
My Goal are to implement additional Hooks in my Themes. To get Agent Informations like Crobjob i need to call to include the functions (i will not rewrite every function again...)

**Comment by own3mall** [comment]
I still don't understand why you need this, but could you give me an example?

**Comment by own3mall** [comment]
Ok, well I changed it here:

[Reference Path Directly from Script Location](https://github.com/OpenGamePanel/OGP-Website/pull/586)

**Pull request closed without merging**
