### PR TITLE
Additional Check Display Public IP Support

### PR DESCRIPTION
**Pull request by oNdsen**
Also added a small colspan Fix on mini Start when an Error exists

### CODE REVIEW

**Comment by own3mall** [comment]
Why the colspan change?   Screenshot of why you changed it?

**Comment by oNdsen** [comment]
You only see it when you have Table Styles:
[https://picload.org/image/riwglopw/without.png](url)
[https://picload.org/image/riwglopw/without.png](url)

**Comment by own3mall** [comment]
Um both URLs are the same.

**Comment by oNdsen** [comment]
Oh damn... ;-)
[https://picload.org/image/riwglowr/with.png](url)

**Comment by oNdsen** [comment]
Other Option is to add an empty <td/> but i prefer the Colspan.

**Comment by own3mall** [comment]
Hope this doesn't affect the default theme negatively...

**Comment by oNdsen** [comment]
Nope it doesnt. Allready tested it.

**Pull request merged**
