### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Bebiano86**
new datePickerInput check method

### CODE REVIEW

**Comment by Zorrototo** [comment]
Can you give more info about why you created this PR?

**Comment by Bebiano86** [comment]
check never works as intended because the object "always exists", only with a length equal to its structure
in this case 0 (because there is no
hence the .length
which confirms whether the object is greater than 0

**Comment by Zorrototo** [comment]
Is the issue happening only with this theme or is it a global issue wit hall themes? From my understanding it is a global issue but this is only with this theme that it seems to have happened (can't try right now).

**Comment by Bebiano86** [comment]
it is a global problem the error is present in all themes.

**Comment by oNdsen** [comment]
@Bebiano86 You check for boolean (datePickerInput.length). Please check if the Value is greather than 0 otherwise it will not work.
Check my example: https://github.com/oNdsen/OGP-Website/commit/bcaa19b518944a855ea152fe6144bac981c83ffd
@Zorrototo Yes it is a global Problem.

**Comment by Bebiano86** [comment]
@oNdsen done

**Comment by own3mall** [comment]
@oNdsen, this is not true.  Just checking for .length should be sufficient.  However, both work.

**Comment by oNdsen** [comment]
Interessting, didnt worked with boolean check on my side. But maybe i just was too quick ;) Thanks for Check!

**Comment by own3mall** [comment]
Fixed in https://github.com/OpenGamePanel/OGP-Website/pull/585

Thanks

**Pull request closed without merging**
